shell.run("delete .browser")
term.clear()
sleep(1)
shell.run("wget https://raw.githubusercontent.com/Eevvaann6/CC-Browser/master/BrowserApp.lua .browser")
term.clear()
term.setCursorPos(1, 1)
print("Starting...")
shell.run(".browser")
